FROM nginx:1.25.4-alpine3.18
EXPOSE 4300
RUN rm /etc/nginx/conf.d/default.conf

# Copy NGINX configurations
COPY ./eng/docker/nginx.conf /etc/nginx/nginx.conf
COPY ./eng/docker/nginx-default.conf /etc/nginx/conf.d/default.conf

# Copy website
COPY ./dist/code-review-analyzer/browser /usr/share/nginx/html
COPY ./eng/docker/nginx-start.sh .

ENTRYPOINT ["sh", "nginx-start.sh"]