name: ChatGPT Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened]
permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
      - uses: GrantBirki/git-diff-action@v2.4.0
        id: git-diff
        with:
          raw_diff_file_output: diff.txt
          file_output_only: "true"

      - name: Perform Code Review With gpt-4
        id: code_review_suggestions
        run: |
          # get the code changes
          changed_code=$(cat ${{steps.git-diff.outputs.raw-diff-path}})
          # echo "PR Changes $changed_code"

          escaped_code=$(echo $"changed_files" | jq -s -R -r @json)

          response=$(curl https://api.openai.com/v1/chat/completions \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.OPENAI_API_KEY }}" \
            -d '{
              "model": "o3-mini-high",
              "messages": [
                {"role": "system", "content": "${{ vars.CODE_REVIEW_PROMPT }}"},
                {"role": "user", "content": "$escaped_code"}
              ],
              "temperature": 0.7
            }')
          echo "This is the response $response"


