name: ChatGPT Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened]
permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0

      - uses: sshnaidm/gpt-code-review-action@v2.0
        with:
          openai-key: ${{ secrets.OPENAI_API_KEY }}
          model: 'o3-mini-high'
          max-length: 8000
          prompt: 'Suggest code syntax, performance, clarity improvements for this code.'
          post-if-error: false
      # - name: Run ChatGPT Code Review
      #   uses: ./.github/actions/chatgpt-review
      #   env:
      #     OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
